version: 0.2 
env:
  shell: bash
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - python --version
      - pip --version
      - echo Instando dependencias
      - cd app
      - pip install -r requirements.txt
  build: 
    commands: 
      - echo Executando o testUnit
      - make test